Add error return if FEATURE_MIGUX_REQUIREMENTS is not found when ENABLE_MIGUX is enabled. Also remove the deprecated expand_sources

diff --git a/Dockerfile.rocky9 b/Dockerfile.rocky9
--- a/Dockerfile.rocky9
+++ b/Dockerfile.rocky9
@@ -905,20 +905,13 @@ RUN echo "Clone migrid: ${MIG_GIT_REPO} ${MIG_GIT_BRANCH} ${MIG_GIT_REV}" && \
     echo "migrid version: ${MIG_GIT_REPO} ${MIG_GIT_BRANCH} ${MIG_GIT_REV}" > \
         ./active-migrid-version.txt
 
-# With the repository available, we have access to definitions and scripts
-# within it. As such, we can gather any dependencies defined there.
-
-RUN if [ -e "$MIG_ROOT/envhelp/scripts/expand_sources.py" ]; then \
-    "$MIG_ROOT/envhelp/scripts/expand_sources.py" --use-wget; fi
-
-# In a per-feature requirements file future, we will have something generic
-# across the features here. For now, perform one-off logic to arrange for a
-# package of migrid UX that we can install; then do so.
-
 # Section for installing migrid-ux
 RUN echo "Installing migrid-ux: ${ENABLE_MIGUX}"
 ENV FEATURE_MIGUX_REQUIREMENTS="$MIG_ROOT/mig/install/requirements/migux-requirements.txt"
 USER root
+RUN if [ "${ENABLE_MIGUX}" == "True" ] && [ ! -e "${FEATURE_MIGUX_REQUIREMENTS}" ]; then \
+    echo "ERROR: migrid-ux was enabled but requirements file not found at: ${FEATURE_MIGUX_REQUIREMENTS}"; \
+    exit 1; fi
 RUN if [ "${ENABLE_MIGUX}" == "True" ] && [ -e "${FEATURE_MIGUX_REQUIREMENTS}" ]; then \
     python3 -m pip install -r "${FEATURE_MIGUX_REQUIREMENTS}"; fi
 
