Rework openidc module upgrade to fail hard on any install problems to avoid silent error e.g. upon new upstream releases when older el7 packages may disapper without notice. Upgrade all platforms to latest stable openidc module release.

diff --git a/Dockerfile.rocky8 b/Dockerfile.rocky8
--- a/Dockerfile.rocky8
+++ b/Dockerfile.rocky8
@@ -458,13 +458,20 @@ RUN echo "UPGRADE_MOD_AUTH_OPENIDC: $UPGRADE_MOD_AUTH_OPENIDC"
 RUN if [ "$UPGRADE_MOD_AUTH_OPENIDC" = "True" ]; then \
 	echo "upgrading mod_auth_openidc from upstream centos7 rpm" \
 	&& yum update -y \
+	# IMPORTANT: fail hard if any of these installs don't succeed e.g. due
+	#            to missing upstream packages to avoid silent errors later.
 	&& yum install -y jansson-devel \
-                # NOTE: recent cjose is already included in rocky8+
-                #https://github.com/OpenIDC/cjose/releases/download/v0.6.2.2/cjose-0.6.2.2-1.el8.x86_64.rpm \
-                cjose \
-                https://github.com/OpenIDC/mod_auth_openidc/releases/download/v2.4.14.4/mod_auth_openidc-2.4.14.4-1.el8.x86_64.rpm \
-                && yum clean all \
-                && rm -fr /var/cache/yum; \
+	# NOTE: recent cjose is already included in rocky8+
+	&& yum install -y \
+		cjose \
+		#https://github.com/OpenIDC/cjose/releases/download/v0.6.2.2/cjose-0.6.2.2-1.el8.x86_64.rpm \
+	&& yum install -y \
+		https://github.com/OpenIDC/mod_auth_openidc/releases/download/v2.4.15.1/mod_auth_openidc-2.4.15.1-1.el8.x86_64.rpm \
+	&& yum clean all \
+	&& rm -fr /var/cache/yum; \
+	if [ $? -ne 0 ]; then \
+		echo "Upgrade Apache OpenID Connect module failed!"; exit 1; \
+	fi; \
     fi;
 
 
